{% set name = "monai" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Project-MONAI/MONAI/archive/refs/tags/{{ version }}.tar.gz
  sha256: e370e1fcd78854fb22c2414fa7419c15ff5afce67b923ce666d0f12979015136

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - numpy >=1.20
    - pytorch >=1.9

test:
  imports:
    - monai
    - monai.losses.dice
    - monai.networks.nets.unet
    - monai.transforms.spatial.dictionary
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://monai.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: AI Toolkit for Healthcare Imaging
  description: |
    MONAI is a PyTorch-based, open-source framework for deep learning in
    healthcare imaging, part of PyTorch Ecosystem.
  doc_url: https://docs.monai.io/en/stable/
  dev_url: https://github.com/Project-MONAI/MONAI
  doc_source_url: https://github.com/Project-MONAI/MONAI/tree/dev/docs

extra:
  recipe-maintainers:
    - KumoLiu
    - mdraw
    - wyli
