{% set name = "monai" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Project-MONAI/MONAI/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6534b0a41a4c6d925b65580986c0b39ef7d88d11bc704fc85b966b6e31e5851b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy >=1.17
    - pytorch >=1.7

test:
  imports:
    - monai
    - monai.losses.dice
    - monai.networks.nets.unet
    - monai.transforms.spatial.dictionary
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://monai.io/
  license: Apache-2.0
  license_file: LICENSE
  summary: AI Toolkit for Healthcare Imaging
  description: |
    MONAI is a PyTorch-based, open-source framework for deep learning in
    healthcare imaging, part of PyTorch Ecosystem.
  doc_url: https://docs.monai.io/en/stable/
  dev_url: https://github.com/Project-MONAI/MONAI
  doc_source_url: https://github.com/Project-MONAI/MONAI/tree/dev/docs

extra:
  recipe-maintainers:
    - mdraw
